TrainReader:
  dataloader: dataset,BatchBalancedDataset
  select_data: 'ArT_train-LSVT_train-MTWI_train-RCTW17_train-ReCTS_train'
  batch_ratio: '0.2-0.2-0.2-0.2-0.2'
  total_data_usage_ratio: 1.0
  padding: True
  augment: False
  batch_size: 128
  shuffle: True
  num_workers: 8
  lmdb_sets_dir: 

EvalReader:
  dataloader: dataset,evaldataloader
  select_data: '/'
  batch_size: 64
  padding: True
  shuffle: True
  num_workers: 8
  lmdb_sets_dir: 

TestReader:
  dataloader: dataset,evaldataloader
  select_data: '/'
  batch_size: 2
  padding: True
  shuffle: True
  num_workers: 0
  lmdb_sets_dir: 

Global:
  algorithm: CDistNet
  is_train: True
  use_gpu: True
  gpu_num: '0'
  device: cuda:0
  num_iters: 800000
  highest_acc_save_type: False
  data_filtering_off: False
  resumed_optimizer: False
  batch_max_length: 50
  print_batch_step: 10
  save_model_dir: output/CDistNet_20211129
  eval_batch_step: 2000
  image_shape: [1, 64, 256]
  character_type: ch
  padding_idx: 0
  use_space_char: false
  character_dict_path: 
  seed: 1234
  pretrain_weights:
  save_inference_dir:
  infer_img:

Architecture:
  function: model.cdistnet,CDistNet

VisualModule:
  layers: [1, 2, 5, 3]
  n_layer: 3
  d_model: 256
  d_inner: 1024
  n_head: 8
  d_k: 32
  d_v: 32
  dropout: 0.1

PositionalEmbedding:
  d_onehot: 256
  d_hid: 256
  n_position: 200

SemanticEmbedding:
  d_model: 256
  rnn_layers: 2
  rnn_dropout: 0
  d_k: 32
  attn_dropout: 0.1

MDCDP:
  n_layer_sae: 1
  d_model_sae: 256
  d_inner_sae: 1024
  n_head_sae: 8
  d_k_sae: 32
  d_v_sae: 32
  n_layer: 3
  d_model: 256
  d_inner: 1024
  n_head: 8
  d_k: 32
  d_v: 32
  dropout: 0.1

Loss:
  function: loss,AttnLoss
  blank_idx: 0

Optimizer:
  function: adam
  base_lr: 0.001
  momentum: 0.9
  weight_decay: 1.0e-4
  lr_decay_epoch: 10
  max_epoch: 1000
  

